### ISSUE TITLE
Problem with commit's author

### ISSUE THREAD

**Issue by uetam** [truveris/hg-mattermost#1]
On my mattermost all comits are made by system user who is currently running apache process:
`www-data@SERVER pushes 1 changeset to "REPO":`
how can i change this to work properly and display real name of commit author?

**Comment by tamentis** [comment]
This does not seem to be a message emitted by `hg-mattermost`:
> `www-data@SERVER pushes 1 changeset to "REPO":`

Could you copy-paste the actual message and ideally the corresponding output from `hg log` for that commit?
